export const showcaseImages = [
  {
    name: 'formbuilder',
    src: '/img/showcase/formbuilder-1.png',
    text: 'Form Builder',
    from: 'company',
    language: ['Nuxt', 'Appwrite', 'typescript', 'html', 'css', 'tailwind'],
  },
  {
    name: 'phase10',
    src: '/img/showcase/phase10-1.png',
    text: 'Phase 10 ',
    from: 'school',
    language: ['Angular', 'socket.io', 'phpmyadmin', 'typescript', 'html', 'css'],
  },
  {
    name: 'spotify',
    src: '/img/showcase/spotify-1.png',
    text: 'Spotify Clone',
    from: 'school',
    language: ['Symfony', 'sqlite', 'twig', 'css'],
  },
  { src: '/img/showcase/formbuilder-1.png', text: 'Form Builder ' },
  { src: '/img/showcase/phase10-1.png', text: 'Phase 10 ' },
  { src: '/img/showcase/spotify-1.png', text: 'Spotify Clone' },
  { src: '/img/showcase/formbuilder-1.png', text: 'Form Builder ' },
  { src: '/img/showcase/phase10-1.png', text: 'Phase 10 ' },
  { src: '/img/showcase/spotify-1.png', text: 'Spotify Clone' },
  { src: '/img/showcase/formbuilder-1.png', text: 'Form Builder ' },
  { src: '/img/showcase/phase10-1.png', text: 'Phase 10 ' },
  { src: '/img/showcase/spotify-1.png', text: 'Spotify Clone' },
]
